// Git types
export type {
  FileStatusType,
  FileStatus,
  DiffLine,
  DiffHunk,
  DiffContent,
  GitCommitIdentitySource,
  GitCommitIdentity,
  GitCommitIdentityInputReason,
  GitCommitIdentityReadyState,
  GitCommitIdentityRequiresInputState,
  GitCommitIdentityState,
  GitMutationErrorCode,
  GitMutationErrorMetadata,
  GitMutationErrorResponse,
  CommitPayload,
  CreateBranchPayload,
  GitBranchMutationResult,
  PushPayload,
  GitPushMutationResult,
  CreatePullRequestPayload,
  CreatePullRequestFromRunPayload,
  GitPullRequestSummary,
  GitPullRequestMutationResult,
  GitStatusReady,
  GitStatusNotRepository,
  GitStatusResponse,
  GitDiffRequest,
  StageFilesRequest,
} from "./git.js";

// Credential vault contracts
export {
  CredentialVaultSurfaceSchema,
  CredentialVaultEntrySchema,
  CredentialVaultUnsupportedOperationError,
  type CredentialVaultSurface,
  type CredentialVaultEntry,
  type CredentialVault,
} from "./credential-vault.js";

// Provider/BYOK contracts
export {
  PROVIDER_IDS,
  ProviderIdSchema,
  ProviderCapabilityFlagsSchema,
  ModelDescriptorSchema,
  ProviderCatalogEntrySchema,
  ProviderCatalogResponseSchema,
  ProviderConnectionStateSchema,
  ProviderConnectionSchema,
  ProviderConnectionsResponseSchema,
  BYOKConnectRequestSchema,
  BYOKConnectResponseSchema,
  BYOKDisconnectRequestSchema,
  BYOKDisconnectResponseSchema,
  BYOKValidationModeSchema,
  BYOKValidateRequestSchema,
  BYOKValidateResponseSchema,
  BYOKPreferencesPatchSchema,
  BYOKPreferencesSchema,
  ProviderErrorCodeSchema,
  NormalizedProviderErrorSchema,
  ProviderErrorEnvelopeSchema,
} from "./provider.js";
export type {
  ProviderId,
  ProviderCapabilityFlags,
  ModelDescriptor,
  ProviderCatalogEntry,
  ProviderCatalogResponse,
  ProviderConnectionState,
  ProviderConnection,
  ProviderConnectionsResponse,
  BYOKConnectRequest,
  BYOKConnectResponse,
  BYOKDisconnectRequest,
  BYOKDisconnectResponse,
  BYOKValidationMode,
  BYOKValidateRequest,
  BYOKValidateResponse,
  BYOKPreferencesPatch,
  BYOKPreferences,
  ProviderErrorCode,
  NormalizedProviderError,
  ProviderErrorEnvelope,
} from "./provider.js";

// Run status types
export { RUN_STATUSES } from "./run-status.js";
export type { RunStatus } from "./run-status.js";

// Explicit build/plan mode contract
export { RunModeSchema, DEFAULT_RUN_MODE, type RunMode } from "./run-mode.js";
export {
  PRODUCT_MODES,
  APPROVAL_POLICIES,
  EXECUTION_SCOPES,
  WORKFLOW_INTENTS,
  WORKFLOW_ENTRYPOINTS,
  ProductModeSchema,
  ApprovalPolicySchema,
  ExecutionScopeSchema,
  WorkflowIntentSchema,
  WorkflowEntrypointSchema,
  PERMISSION_RUNTIME_LABELS,
  DEFAULT_PRODUCT_MODE,
  resolveWorkflowIntent,
  mapProductModeToPermissionTuple,
  createEffectivePermissionState,
  derivePermissionLabel,
  type ProductMode,
  type ApprovalPolicy,
  type ExecutionScope,
  type WorkflowIntent,
  type WorkflowEntrypoint,
  type WorkflowIntentResolverInput,
  type EffectivePermissionState,
  type PermissionTuple,
  type PermissionRuntimeLabel,
} from "./permission-policy.js";
export {
  RISKY_ACTION_CATEGORIES,
  APPROVAL_DECISION_KINDS,
  APPROVAL_RESOLUTION_STATUSES,
  ApprovalRequestSchema,
  RiskyActionCategorySchema,
  ApprovalDecisionKindSchema,
  ApprovalResolutionStatusSchema,
  type RiskyActionCategory,
  type ApprovalDecisionKind,
  type ApprovalResolutionStatus,
  type ProposedPersistentRule,
  type ApprovalRequest,
  type ApprovalDecision,
  type PermissionEvaluationResult,
} from "./approval-policy.js";

// Activity feed contract
export {
  ACTIVITY_PART_KINDS,
  COMMENTARY_ACTIVITY_PHASES,
  COMMENTARY_ACTIVITY_STATUSES,
  TOOL_ACTIVITY_STATUSES,
  REASONING_ACTIVITY_STATUSES,
  APPROVAL_ACTIVITY_STATUSES,
  HANDOFF_ACTIVITY_STATUSES,
  TOOL_ACTIVITY_FAMILIES,
  isActivityPart,
  type ActivityPartKind,
  type CommentaryActivityPhase,
  type CommentaryActivityStatus,
  type ToolActivityStatus,
  type ReasoningActivityStatus,
  type ApprovalActivityStatus,
  type HandoffActivityStatus,
  type ToolActivityFamily,
  type ActivityPartBase,
  type TextActivityPart,
  type CommentaryActivityPart,
  type ReasoningActivityPart,
  type ToolActivityPart,
  type ApprovalActivityPart,
  type HandoffActivityPart,
  type ReadToolActivityMetadata,
  type SearchToolActivityMetadata,
  type ShellToolActivityMetadata,
  type EditToolActivityMetadata,
  type GitToolActivityMetadata,
  type GenericToolActivityMetadata,
  type ToolActivityMetadata,
  type ActivityPart,
  type ActivityFeedSnapshot,
} from "./activity-feed.js";
export {
  ActivityPartSchema,
  ActivityFeedSnapshotSchema,
  parseActivityPart,
  safeParseActivityPart,
  parseActivityFeedSnapshot,
  safeParseToolActivityMetadata,
} from "./activity-feed.zod.js";

// Run event types
export {
  MESSAGE_TRANSCRIPT_PHASES,
  MESSAGE_TRANSCRIPT_STATUSES,
  RUN_EVENT_TYPES,
  RUN_WORKFLOW_STEPS,
  type EventSource,
  type MessageTranscriptPhase,
  type MessageTranscriptStatus,
  type RunEventType,
  type RunEventEnvelope,
  type RunWorkflowStep,
  isRunEvent,
  isRunEventOfType,
  // Event types
  type RunStartedEvent,
  type RunStatusChangedEvent,
  type RunProgressEvent,
  type ApprovalRequestedEvent,
  type ApprovalResolvedEvent,
  type MessageEmittedEvent,
  type ToolRequestedEvent,
  type ToolStartedEvent,
  type ToolOutputAppendedEvent,
  type ToolCompletedEvent,
  type ToolFailedEvent,
  type RunCompletedEvent,
  type RunFailedEvent,
  type RunEvent,
  // Payload types
  type RunStartedPayload,
  type RunStatusChangedPayload,
  type RunProgressPayload,
  type ApprovalRequestedPayload,
  type ApprovalResolvedPayload,
  type MessageEmittedPayload,
  type ToolRequestedPayload,
  type ToolStartedPayload,
  type ToolOutputAppendedPayload,
  type ToolCompletedPayload,
  type ToolFailedPayload,
  type RunCompletedPayload,
  type RunFailedPayload,
} from "./run-events.js";

// Zod validation
export {
  parseRunEvent,
  safeParseRunEvent,
  validateEventEnvelope,
  getEventPayloadSchema,
} from "./run-events.zod.js";

// Chat response events (NDJSON streaming)
export {
  CHAT_RESPONSE_EVENT_TYPES,
  isChatResponseEvent,
  isChatResponseEventOfType,
  serializeChatResponseEvent,
  parseChatResponseEvent,
  type ChatResponseEventType,
  type ChatResponseEvent,
  type TextDeltaPayload,
  type ToolCallPayload,
  type ToolResultPayload,
  type ToolErrorPayload,
  type RunStatusPayload,
  type FinalPayload,
  type TextDeltaEvent,
  type ToolCallEvent,
  type ToolResultEvent,
  type ToolErrorEvent,
  type RunStatusEvent,
  type FinalEvent,
  type ChatResponseEventUnion,
} from "./chat-response-events.js";

// Runtime debug metadata
export {
  buildRuntimeFingerprint,
  buildRuntimeHeaders,
  collectFeatureFlagSnapshot,
  createRuntimeIdentity,
  resolveRuntimeGitSha,
  type RuntimeHeaders,
  type RuntimeIdentity,
} from "./runtime-debug.js";

// Chat response contract (v1 frozen DTOs for provider parity)
export {
  CHAT_RESPONSE_PROTOCOL_VERSION,
  ChatResponseEventSchema,
  validateChatResponseEvent,
  parseChatResponseEvent as parseChatResponseEventContract,
  safeParseChatResponseEvent,
  type ChatResponseEvent as ChatResponseEventContract,
} from "./chat-response-contract.js";

// External contract freeze manifest (chat/provider/tool/event)
export {
  EXTERNAL_CONTRACT_FREEZE_VERSION,
  EXTERNAL_CONTRACT_MANIFEST,
  EXTERNAL_CHAT_CONTRACT,
  EXTERNAL_PROVIDER_CONTRACT,
  EXTERNAL_TOOL_CONTRACT,
  EXTERNAL_EVENT_CONTRACT,
} from "./external-contracts.js";

// Client SDK readiness pack (web/desktop/cli)
export {
  SdkConsumerSurfaceSchema,
  SdkReadinessStatusSchema,
  SdkChecklistItemSchema,
  SdkReferenceExamplesSchema,
  SdkSurfaceReadinessSchema,
  SdkReadinessPackSchema,
  SDK_READINESS_PACK_V1,
  getSdkReadinessPack,
  validateSdkReadinessPack,
  collectSdkBlockers,
  type SdkConsumerSurface,
  type SdkReadinessStatus,
  type SdkChecklistItem,
  type SdkReferenceExamples,
  type SdkSurfaceReadiness,
  type SdkReadinessPack,
} from "./sdk-readiness.js";

// Protocol versioning + compatibility policy (v1)
export {
  PROTOCOL_POLICY_VERSION,
  PROTOCOL_POLICY_DOCUMENT_PATH,
  PROTOCOL_CURRENT_VERSION,
  PROTOCOL_MIN_COMPATIBLE_VERSION,
  PROTOCOL_DEPRECATION_WINDOW_DAYS,
  PROTOCOL_CHANGE_CATEGORY,
  ProtocolChangeAssessmentSchema,
  evaluateProtocolChange,
  isProtocolVersionSupported,
  validateProtocolPolicyReference,
  type ProtocolChangeCategory,
  type ProtocolChangeAssessment,
  type ProtocolCompatibilityDecision,
} from "./protocol-policy.js";

// Compatibility layer
export {
  LEGACY_EVENT_NAMES,
  isLegacyEventName,
  getCanonicalEventType,
  convertLegacyEvent,
  normalizeEvent,
} from "./run-events.compat.js";

// BYOK module (new architecture)
// Note: Use explicit named exports to avoid conflicts with legacy v2 BYOK types
export {
  BYOKCredentialSchema,
  BYOKCredentialDTOSchema,
  BYOKPreferenceSchema,
  BYOKPreferencePatchSchema,
  BYOKResolutionSchema,
  BYOKResolveRequestSchema,
  BYOKErrorCodeSchema,
  BYOKErrorSchema,
  BYOKErrorEnvelopeSchema,
  BYOKValidationErrorDetailSchema,
  BYOKValidationErrorResponseSchema,
  BYOKCredentialConnectRequestSchema,
  BYOKCredentialUpdateRequestSchema,
  BYOKCredentialValidateRequestSchema,
  BYOKCredentialValidateResponseSchema,
  BYOKProviderModelsResponseSchema,
  BYOKProviderSlugSchema,
  BYOKModelDiscoveryViewSchema,
  BYOKModelDiscoverySurfaceSchema,
  BYOKModelDiscoverySourceSchema,
  BYOKModelPricingSchema,
  BYOKModelPopularitySignalsSchema,
  BYOKModelPopularityScoreSchema,
  BYOKModelCapabilitySchema,
  BYOKModelOutputModalitySchema,
  BYOKDiscoveredProviderModelSchema,
  BYOKDiscoveredProviderModelsPageSchema,
  BYOKDiscoveredProviderModelsMetadataSchema,
  BYOKDiscoveredProviderModelsQuerySchema,
  BYOKDiscoveredProviderModelsResponseSchema,
  BYOKDiscoveredProviderModelsRefreshResponseSchema,
  BYOKPreferencesUpdateRequestSchema,
  RETRYABLE_ERRORS,
  isRetryableError,
  AUTH_ERRORS,
  isAuthError,
  createBYOKError,
  createBYOKErrorInternal,
  ProviderAuthModeSchema,
  ProviderAdapterFamilySchema,
  ProviderLaunchStageSchema,
  ProviderValidationAuthModeSchema,
  ProviderRegistryEntrySchema,
  ProviderRegistrySchema,
  BUILTIN_PROVIDERS,
  getBuiltinRegistry,
  findBuiltinProvider,
  isKnownProvider,
  getKnownProviderIds,
  isLaunchVisibleProvider,
  isLaunchSupportedProvider,
  getLaunchVisibleProviders,
  getLaunchSupportedProviders,
  AXIS_PROVIDER_ID,
  ProviderProductEnvironmentSchema,
  ProviderProductPolicySchema,
  createProviderProductPolicy,
  canShowProviderInPrimaryUi,
  canUseProviderAtRuntime,
  canUseProviderRuntimeFallback,
  canPreloadProvider,
  // API contracts (exclude to avoid conflicts with v2)
  type BYOKCredential,
  type BYOKCredentialDTO,
  type BYOKPreference,
  type BYOKPreferencePatch,
  type BYOKResolution,
  type BYOKResolveRequest,
  type BYOKErrorCode,
  type BYOKError,
  type BYOKErrorInternal,
  type BYOKErrorEnvelope,
  type BYOKValidationErrorDetail,
  type BYOKValidationErrorResponse,
  type ProviderAuthMode,
  type ProviderAdapterFamily,
  type ProviderLaunchStage,
  type ProviderValidationAuthMode,
  type BYOKCredentialConnectRequest,
  type BYOKCredentialUpdateRequest,
  type BYOKCredentialValidateRequest,
  type BYOKCredentialValidateResponse,
  type BYOKProviderModelsResponse,
  type BYOKProviderSlug,
  type BYOKModelDiscoveryView,
  type BYOKModelDiscoverySurface,
  type BYOKModelDiscoverySource,
  type BYOKModelPricing,
  type BYOKModelPopularitySignals,
  type BYOKModelPopularityScore,
  type BYOKModelCapability,
  type BYOKModelOutputModality,
  type BYOKDiscoveredProviderModel,
  type BYOKDiscoveredProviderModelsPage,
  type BYOKDiscoveredProviderModelsMetadata,
  type BYOKDiscoveredProviderModelsQuery,
  type BYOKDiscoveredProviderModelsResponse,
  type BYOKDiscoveredProviderModelsRefreshResponse,
  type BYOKPreferencesUpdateRequest,
  type ProviderRegistryEntry,
  type ProviderRegistry,
  type ProviderProductEnvironment,
  type ProviderProductPolicy,
} from "./byok/index.js";
